
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # You can change this to your desired value (e.g., create, update, none)
    show-sql: true # Set to true to see SQL statements in logs
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296

server:
  port: 8084 # Change to the desired port for your Spring Boot application

logging:
  level:
    root: INFO # Adjust log levels as needed for your application

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
